[project]
name = "adat_rx"
version = "0.2.0"

[build]
sources = ["src"]
target = { type = "directory", path = "target" }

[test]
simulator = "verilator"
waveform_format = "fst"

[test.verilator]
compile_args = ["-Wno-fatal"]
