name: CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
        types: [opened, synchronize, reopened]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6
            - uses: extractions/setup-just@v3
            - uses: veryl-lang/setup-verilator@v1
            - name: install veryl
              run: |
                  cargo install verylup
                  verylup setup
            - name: Unit tests
              run: |
                  cd sim/verilator
                  just unit-tests
            - name: Tests
              run: |
                  cd sim/verilator
                  just run
